apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "consumer.name" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "consumer.name" . }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}